schema_version = "1.0.0"
id = "flashaov"
name = "Flash AOV"
version = "1.3.0"
tagline = "AOV Config Assistant Tools"
maintainer = "FlashAOV"
type = "add-on"
tags = ["3D View", "Compositing"]
blender_version_min = "4.0.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/VFX-DONG"
copyright = ["2025 flashaov"]

