schema_version = "1.0.0"
blender_version_min = "4.2.0"
id = "flash_aov"
maintainer = "ZhenDong"
name = "Flash AOV"
tagline = "AOV Config Assistant Tools"
license = ["SPDX:GPL-3.0-or-later"]
type = "add-on"
version = "1.5.0"
tags = ["3D View", "Compositing"]
website = "https://github.com/VFX-DONG"
